name: Build/release

on: push

jobs:
  package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Make distributables using Electron Forge
        run: yarn make

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: make
          path: |
            out/make/
          retention-days: 3
